### PR TITLE
Use npx for astro commands

### PR DESCRIPTION
**Pull request by tomayac**
…So astro doesn't have to be installed globally.

### CODE REVIEW

**Comment by argyleink** [comment]
it's not installed globally, it's installed per the project?

**Comment by tomayac** [comment]
Sure, but without `npx` it will look globally and fail.

**Comment by tomayac** [comment]
See the [docs](https://www.npmjs.com/package/npx).

**Comment by argyleink** [comment]
i dont understand, maybe let's chat about it?
we have a versioned astro dep in the repo, in case you have astro in another project with another version? is npx from package.json some new trend?

**Comment by tomayac** [comment]
See the screenshot of my terminal session and note the difference in the scripts, one with, and one without `npx`:

Screen Shot 2021-12-01 at 13 10 29

**Comment by lyqht** [comment]
This will happen if your NPM package paths are not configured properly, it's not an issue because of npx or astro.

**Comment by tomayac** [comment]
Additional background:
- [Docs of `create-react-app`](https://reactjs.org/docs/create-a-new-react-app.html#:~:text=npx%20on%20the%20first%20line%20is%20not%20a%20typo%20%E2%80%94%20it%E2%80%99s%20a%20package%20runner%20tool%20that%20comes%20with%20npm%205.2%2B.).
- [Introduction of `npx`](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b).

**Comment by argyleink** [comment]
these examples confirm my usages of npx, which are one time use cases? i dont see examples where they say to use npx from your package.json scripts exclusively, which is what's proposed in this PR? the PR says "so astro doesnt need to be installed globally", which this project doesnt require. no where do we say run `npm i -g astro` before running the build? 

again, if you want to save typing, we can video chat about it. i'm a fan of npx, use it for all sorts of neat things. but i've never seen it used in package.json scripts to avoid global installs. not sure we have the problem this pr wants to solve?

**Comment by tomayac** [comment]
Weird, it was indeed a problem with my environment. I moved to a new machine recently and switched from bash to zsh. Probably related somehow… Closing.

**Pull request closed without merging**
